# Generated by Django 5.2.7 on 2025-11-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(help_text='Ejemplo: Proyección 2025 - Banco Agrícola', max_length=200, verbose_name='Nombre de la proyección')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la proyección', verbose_name='Descripción')),
                ('origen', models.CharField(choices=[('CALCULADO', 'Calculado en la aplicación'), ('ARCHIVO', 'Subido desde archivo Excel')], default='ARCHIVO', max_length=20, verbose_name='Origen de datos')),
                ('archivo', models.FileField(blank=True, help_text='Archivo Excel con datos de proyección', null=True, upload_to='proyecciones/%Y/%m/', verbose_name='Archivo Excel')),
                ('datos_grafico', models.JSONField(blank=True, help_text='Datos procesados para visualización', null=True, verbose_name='Datos del gráfico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proyección Financiera',
                'verbose_name_plural': 'Proyecciones Financieras',
                'db_table': 'proyeccion_financiera',
                'ordering': ['-creado_en'],
            },
        ),
    ]
