# Generated by Django 5.2.7 on 2025-11-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('graficos_financieros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('año', models.IntegerField(db_column='anio', help_text='Año de la proyección', verbose_name='Año')),
                ('mes', models.IntegerField(help_text='Mes (1-12)', verbose_name='Mes')),
                ('metodo', models.CharField(help_text='Incremento Porcentual, Incremento Absoluto, Mínimos Cuadrados', max_length=100, verbose_name='Método de proyección')),
                ('valor_proyectado', models.DecimalField(decimal_places=2, help_text='Valor de venta proyectado', max_digits=15, verbose_name='Valor proyectado')),
            ],
            options={
                'verbose_name': 'Proyección de Venta',
                'verbose_name_plural': 'Proyecciones de Ventas',
                'db_table': 'proyeccion_ventas',
                'ordering': ['año', 'mes'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='proyeccionfinanciera',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones_financieras', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='AnalisisRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(help_text='Ejemplo: Análisis de Ratios 2022-2024', max_length=200, verbose_name='Nombre del Análisis')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('datos_grafico', models.JSONField(blank=True, null=True, verbose_name='Datos del Gráfico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ratios', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Análisis de Ratios',
                'verbose_name_plural': 'Análisis de Ratios',
                'db_table': 'analisis_ratio',
                'ordering': ['-creado_en'],
            },
        ),
    ]
