# Generated by Django 5.2.7 on 2025-11-11 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficos_financieros', '0001_initial'),  # Actualizado
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatioFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(help_text='Ejemplo: Razón Corriente, Prueba Ácida', max_length=200, verbose_name='Nombre del Ratio')),
                ('formula_display', models.CharField(help_text='Ejemplo: Activo Corriente / Pasivo Corriente', max_length=500, verbose_name='Fórmula')),
                ('categoria', models.CharField(help_text='Ejemplo: Liquidez, Endeudamiento, Rentabilidad', max_length=100, verbose_name='Categoría')),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Promedio General')),
            ],
            options={
                'verbose_name': 'Ratio Financiero',
                'verbose_name_plural': 'Ratios Financieros',
                'db_table': 'ratio_financiero',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AnalisisRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(help_text='Ejemplo: Análisis de Ratios 2022-2024', max_length=200, verbose_name='Nombre del Análisis')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('datos_grafico', models.JSONField(blank=True, null=True, verbose_name='Datos del Gráfico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ratios', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Análisis de Ratios',
                'verbose_name_plural': 'Análisis de Ratios',
                'db_table': 'analisis_ratio',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ValorRatioCalculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('año', models.IntegerField(help_text='Año del cálculo (Ej: 2022, 2023, 2024)', verbose_name='Año')),
                ('valor_calculado', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor Calculado')),
                ('parametro_sectorial', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Parámetro Sectorial')),
                ('promedio_sector', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Promedio del Sector')),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Promedio General')),
                ('superior_parametro_sectorial', models.BooleanField(default=False, verbose_name='Supera Parámetro Sectorial')),
                ('superior_promedio_sector', models.BooleanField(default=False, verbose_name='Supera Promedio del Sector')),
                ('superior_promedio_general', models.BooleanField(default=False, verbose_name='Supera Promedio General')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_ratios', to='empresas.empresa', verbose_name='Empresa')),
                ('ratio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='analisis.ratiofinanciero', verbose_name='Ratio')),
                ('usuario_calculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que calculó')),
            ],
            options={
                'verbose_name': 'Valor de Ratio Calculado',
                'verbose_name_plural': 'Valores de Ratios Calculados',
                'db_table': 'valor_ratio_calculado',
                'ordering': ['empresa', 'ratio', '-año'],
                'unique_together': {('empresa', 'ratio', 'año')},
            },
        ),
    ]
