# Generated by Django 5.2.8 on 2025-11-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_ratiofinanciero_componenteratio_mapeocuentaratio'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatioReferenciaSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('valor_optimo', models.DecimalField(blank=True, decimal_places=4, help_text='Valor de referencia óptimo para este ratio en el sector', max_digits=10, null=True, verbose_name='Valor Óptimo')),
                ('ratio_financiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_sector', to='catalogos.ratiofinanciero', verbose_name='Ratio Financiero')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios_referencia', to='empresas.sector', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Referencia de Ratio por Sector',
                'verbose_name_plural': 'Referencias de Ratios por Sector',
                'db_table': 'ratio_referencia_sector',
                'ordering': ['ratio_financiero__categoria', 'ratio_financiero__nombre'],
                'unique_together': {('ratio_financiero', 'sector')},
            },
        ),
    ]
