# Generated by Django 5.2.8 on 2025-11-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratioreferenciasector',
            name='promedio_sector',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ratio promedio de las empresas clasificadas en este sector', max_digits=10, null=True, verbose_name='Promedio del Sector'),
        ),
    ]
