# Generated by Django 5.2.8 on 2025-11-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_agregar_tipo_resultado'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('año', models.IntegerField(help_text='Año del estado financiero', verbose_name='Año')),
                ('tipo', models.CharField(choices=[('BALANCE_GENERAL', 'Balance General'), ('ESTADO_RESULTADOS', 'Estado de Resultados')], max_length=20, verbose_name='Tipo de estado financiero')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_financieros', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Estado Financiero',
                'verbose_name_plural': 'Estados Financieros',
                'db_table': 'estado_financiero',
                'ordering': ['-año', 'tipo', 'empresa'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstadoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la cuenta en el estado financiero', max_digits=15, verbose_name='Monto')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_estados', to='catalogos.cuentacontable', verbose_name='Cuenta Contable')),
                ('estado_financiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estados.estadofinanciero', verbose_name='Estado Financiero')),
            ],
            options={
                'verbose_name': 'Item de Estado Financiero',
                'verbose_name_plural': 'Items de Estados Financieros',
                'db_table': 'item_estado_financiero',
                'ordering': ['cuenta_contable__codigo', 'cuenta_contable__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='estadofinanciero',
            index=models.Index(fields=['empresa', 'año', 'tipo'], name='estado_fina_empresa_e0d0ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estadofinanciero',
            unique_together={('empresa', 'año', 'tipo')},
        ),
        migrations.AddIndex(
            model_name='itemestadofinanciero',
            index=models.Index(fields=['estado_financiero', 'cuenta_contable'], name='item_estado_estado__133802_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemestadofinanciero',
            unique_together={('estado_financiero', 'cuenta_contable')},
        ),
    ]
