# Generated by Django 5.2.8 on 2025-11-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadofinanciero',
            name='tipo',
            field=models.CharField(choices=[('BALANCE_GENERAL', 'Balance General'), ('ESTADO_RESULTADOS', 'Estado de Resultados')], max_length=20, verbose_name='Tipo de Estado Financiero'),
        ),
    ]
