# Generated by Django 5.2.8 on 2025-11-11 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0005_ratiofinanciero_promedio_general'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorRatioCalculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('año', models.PositiveIntegerField(verbose_name='Año')),
                ('valor_calculado', models.DecimalField(blank=True, decimal_places=4, help_text='Valor del ratio calculado para este año', max_digits=15, null=True, verbose_name='Valor Calculado')),
                ('parametro_sectorial', models.DecimalField(blank=True, decimal_places=4, help_text='Valor óptimo sectorial al momento del cálculo', max_digits=10, null=True, verbose_name='Parámetro Sectorial')),
                ('promedio_sector', models.DecimalField(blank=True, decimal_places=4, help_text='Promedio sectorial al momento del cálculo', max_digits=10, null=True, verbose_name='Promedio del Sector')),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=4, help_text='Promedio general al momento del cálculo', max_digits=10, null=True, verbose_name='Promedio General')),
                ('superior_parametro_sectorial', models.BooleanField(default=False, verbose_name='Superior al Parámetro Sectorial')),
                ('superior_promedio_sector', models.BooleanField(default=False, verbose_name='Superior al Promedio del Sector')),
                ('superior_promedio_general', models.BooleanField(default=False, verbose_name='Superior al Promedio General')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_ratios', to='empresas.empresa', verbose_name='Empresa')),
                ('ratio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_calculados', to='catalogos.ratiofinanciero', verbose_name='Ratio Financiero')),
                ('usuario_calculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Generó el Cálculo')),
            ],
            options={
                'verbose_name': 'Valor de Ratio Calculado',
                'verbose_name_plural': 'Valores de Ratios Calculados',
                'db_table': 'valor_ratio_calculado',
                'ordering': ['empresa', 'ratio', '-año'],
                'indexes': [models.Index(fields=['empresa', 'año'], name='valor_ratio_empresa_93ee46_idx'), models.Index(fields=['ratio', 'año'], name='valor_ratio_ratio_i_85adc9_idx')],
                'unique_together': {('empresa', 'ratio', 'año')},
            },
        ),
    ]
