# Generated by Django 5.2.8 on 2025-11-10 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_cuenta', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Catálogo de Cuentas',
                'verbose_name_plural': 'Catálogos de Cuentas',
                'db_table': 'catalogo_cuenta',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(help_text='Ejemplo: 0101', max_length=20, verbose_name='Código de la cuenta')),
                ('nombre', models.CharField(help_text='Ejemplo: Activos corrientes', max_length=200, verbose_name='Nombre de la cuenta')),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=20, verbose_name='Tipo de cuenta')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='catalogos.catalogocuenta', verbose_name='Catálogo')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'cuenta_contable',
                'ordering': ['codigo', 'nombre'],
                'unique_together': {('catalogo', 'codigo')},
            },
        ),
    ]
