# Generated by Django 5.2.8 on 2025-11-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatioFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(help_text='Ejemplo: Razón Corriente, ROE, ROA', max_length=100, unique=True, verbose_name='Nombre del ratio')),
                ('formula_display', models.CharField(help_text='Ejemplo: Activo Corriente / Pasivo Corriente', max_length=255, verbose_name='Fórmula')),
                ('categoria', models.CharField(help_text='Ejemplo: Liquidez, Endeudamiento, Rentabilidad', max_length=50, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Ratio Financiero',
                'verbose_name_plural': 'Ratios Financieros',
                'db_table': 'ratio_financiero',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre_componente', models.CharField(help_text='Ejemplo: Activo Corriente, Utilidad Neta, Patrimonio', max_length=100, verbose_name='Nombre del componente')),
                ('ratio_financiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='catalogos.ratiofinanciero', verbose_name='Ratio Financiero')),
            ],
            options={
                'verbose_name': 'Componente de Ratio',
                'verbose_name_plural': 'Componentes de Ratios',
                'db_table': 'componente_ratio',
                'ordering': ['ratio_financiero', 'nombre_componente'],
                'unique_together': {('ratio_financiero', 'nombre_componente')},
            },
        ),
        migrations.CreateModel(
            name='MapeoCuentaRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('catalogo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_ratios', to='catalogos.catalogocuenta', verbose_name='Catálogo de Cuentas')),
                ('componente_ratio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_cuentas', to='catalogos.componenteratio', verbose_name='Componente de Ratio')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_ratios', to='catalogos.cuentacontable', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name': 'Mapeo de Cuenta a Ratio',
                'verbose_name_plural': 'Mapeos de Cuentas a Ratios',
                'db_table': 'mapeo_cuenta_ratio',
                'ordering': ['catalogo_cuenta', 'componente_ratio'],
                'unique_together': {('catalogo_cuenta', 'componente_ratio')},
            },
        ),
    ]
