# Generated by Django 5.2.8 on 2025-11-10 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_ratiofinanciero_componenteratio_mapeocuentaratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeocuentaratio',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_ratios', to='catalogos.cuentacontable', verbose_name='Cuenta Contable'),
        ),
    ]
