# Generated by Django 5.2.8 on 2025-11-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_mapeocuentaratio_cuenta_contable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacontable',
            name='tipo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('RESULTADO', 'Resultado')], max_length=20, verbose_name='Tipo de cuenta'),
        ),
    ]
