# Generated by Django 5.2.8 on 2025-11-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_agregar_tipo_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratiofinanciero',
            name='promedio_general',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ratio promedio de todas las empresas en el sistema', max_digits=10, null=True, verbose_name='Promedio General'),
        ),
    ]
